### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by gabays** [katabase/3_TaggedData#3]
The fact that all catalogues are in a `Catalogues` folder changes the schema location. Is it useful?

**Comment by alexbartz** [comment]
I think it's useful because of the script `extractor_json.py`, we get all files recursively (see [here](https://github.com/katabase/3_TaggedData/blob/386eea56b2012e03053db1c04bc8530a01cce070/script/extractor_json.py#L93)). 
For the schema location issue, we can maybe simply use GitHub and have something like this :
```xml
<?xml-model href="https://raw.githubusercontent.com/katabase/3_TaggedData/main/schema/odd_katabase.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://raw.githubusercontent.com/katabase/3_TaggedData/main/schema/odd_katabase.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>

**Comment by gabays** [comment]
OK: we should definitely switch to the address of the online schema rather than the local one. With all the repo or just that one?

**Comment by alexbartz** [comment]
Yes I agree. I think with all the repo would be better. If you're ok, I'll do it.

**Comment by gabays** [comment]
OK. Perfect!

**Comment by alexbartz** [comment]
It's done (for the 3 repos) ! :)
